### PR TITLE
Changed React.PropTypes to prop-types package

### PR DESCRIPTION
**Pull request by frontenddeveloping**
React.PropTypes is deprecated as of React v15.5. 
More info https://facebook.github.io/react/docs/typechecking-with-proptypes.html

### CODE REVIEW

**Comment by blixtgord** [comment]
Can we please accept this pull request! @minhtranite @OMantere

**Comment by gnoesiboe** [comment]
I am waiting for this and getting tired of the console warnings. Can this pull request please be accepted and merged?

**Comment by gvdlangenberg** [comment]
Please accept this pull request!

**Comment by martinbroos** [comment]
I'm waiting for this fix as well, please merge.

**Comment by minhtranite** [comment]
Thanks for your PR.

**Comment by gnoesiboe** [comment]
@minhtranite Thanks for merging!

**Pull request merged**
